// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: autoscraper/v1/autoscraper.proto

package autoscraperv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/diegoafg1009/auto-radar-scraping-microservice/pkg/genproto/autoscraper/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AutoScraperServiceName is the fully-qualified name of the AutoScraperService service.
	AutoScraperServiceName = "autoscraper.v1.AutoScraperService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AutoScraperServiceFindByFilterProcedure is the fully-qualified name of the AutoScraperService's
	// FindByFilter RPC.
	AutoScraperServiceFindByFilterProcedure = "/autoscraper.v1.AutoScraperService/FindByFilter"
)

// AutoScraperServiceClient is a client for the autoscraper.v1.AutoScraperService service.
type AutoScraperServiceClient interface {
	FindByFilter(context.Context, *connect.Request[v1.FindByFilterRequest]) (*connect.Response[v1.FindByFilterResponse], error)
}

// NewAutoScraperServiceClient constructs a client for the autoscraper.v1.AutoScraperService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAutoScraperServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AutoScraperServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	autoScraperServiceMethods := v1.File_autoscraper_v1_autoscraper_proto.Services().ByName("AutoScraperService").Methods()
	return &autoScraperServiceClient{
		findByFilter: connect.NewClient[v1.FindByFilterRequest, v1.FindByFilterResponse](
			httpClient,
			baseURL+AutoScraperServiceFindByFilterProcedure,
			connect.WithSchema(autoScraperServiceMethods.ByName("FindByFilter")),
			connect.WithClientOptions(opts...),
		),
	}
}

// autoScraperServiceClient implements AutoScraperServiceClient.
type autoScraperServiceClient struct {
	findByFilter *connect.Client[v1.FindByFilterRequest, v1.FindByFilterResponse]
}

// FindByFilter calls autoscraper.v1.AutoScraperService.FindByFilter.
func (c *autoScraperServiceClient) FindByFilter(ctx context.Context, req *connect.Request[v1.FindByFilterRequest]) (*connect.Response[v1.FindByFilterResponse], error) {
	return c.findByFilter.CallUnary(ctx, req)
}

// AutoScraperServiceHandler is an implementation of the autoscraper.v1.AutoScraperService service.
type AutoScraperServiceHandler interface {
	FindByFilter(context.Context, *connect.Request[v1.FindByFilterRequest]) (*connect.Response[v1.FindByFilterResponse], error)
}

// NewAutoScraperServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAutoScraperServiceHandler(svc AutoScraperServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	autoScraperServiceMethods := v1.File_autoscraper_v1_autoscraper_proto.Services().ByName("AutoScraperService").Methods()
	autoScraperServiceFindByFilterHandler := connect.NewUnaryHandler(
		AutoScraperServiceFindByFilterProcedure,
		svc.FindByFilter,
		connect.WithSchema(autoScraperServiceMethods.ByName("FindByFilter")),
		connect.WithHandlerOptions(opts...),
	)
	return "/autoscraper.v1.AutoScraperService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AutoScraperServiceFindByFilterProcedure:
			autoScraperServiceFindByFilterHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAutoScraperServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAutoScraperServiceHandler struct{}

func (UnimplementedAutoScraperServiceHandler) FindByFilter(context.Context, *connect.Request[v1.FindByFilterRequest]) (*connect.Response[v1.FindByFilterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("autoscraper.v1.AutoScraperService.FindByFilter is not implemented"))
}
