// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: autoscrapper/v1/autoscrapper.proto

package autoscrapperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindByFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	MinYear       uint32                 `protobuf:"varint,3,opt,name=min_year,json=minYear,proto3" json:"min_year,omitempty"`
	MaxYear       uint32                 `protobuf:"varint,4,opt,name=max_year,json=maxYear,proto3" json:"max_year,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,5,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,6,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByFilterRequest) Reset() {
	*x = FindByFilterRequest{}
	mi := &file_autoscrapper_v1_autoscrapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByFilterRequest) ProtoMessage() {}

func (x *FindByFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoscrapper_v1_autoscrapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByFilterRequest.ProtoReflect.Descriptor instead.
func (*FindByFilterRequest) Descriptor() ([]byte, []int) {
	return file_autoscrapper_v1_autoscrapper_proto_rawDescGZIP(), []int{0}
}

func (x *FindByFilterRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *FindByFilterRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *FindByFilterRequest) GetMinYear() uint32 {
	if x != nil {
		return x.MinYear
	}
	return 0
}

func (x *FindByFilterRequest) GetMaxYear() uint32 {
	if x != nil {
		return x.MaxYear
	}
	return 0
}

func (x *FindByFilterRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *FindByFilterRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

type Auto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auto) Reset() {
	*x = Auto{}
	mi := &file_autoscrapper_v1_autoscrapper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auto) ProtoMessage() {}

func (x *Auto) ProtoReflect() protoreflect.Message {
	mi := &file_autoscrapper_v1_autoscrapper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auto.ProtoReflect.Descriptor instead.
func (*Auto) Descriptor() ([]byte, []int) {
	return file_autoscrapper_v1_autoscrapper_proto_rawDescGZIP(), []int{1}
}

func (x *Auto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Auto) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Auto) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Auto) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type FindByFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Autos         []*Auto                `protobuf:"bytes,1,rep,name=autos,proto3" json:"autos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByFilterResponse) Reset() {
	*x = FindByFilterResponse{}
	mi := &file_autoscrapper_v1_autoscrapper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByFilterResponse) ProtoMessage() {}

func (x *FindByFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoscrapper_v1_autoscrapper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByFilterResponse.ProtoReflect.Descriptor instead.
func (*FindByFilterResponse) Descriptor() ([]byte, []int) {
	return file_autoscrapper_v1_autoscrapper_proto_rawDescGZIP(), []int{2}
}

func (x *FindByFilterResponse) GetAutos() []*Auto {
	if x != nil {
		return x.Autos
	}
	return nil
}

var File_autoscrapper_v1_autoscrapper_proto protoreflect.FileDescriptor

const file_autoscrapper_v1_autoscrapper_proto_rawDesc = "" +
	"\n" +
	"\"autoscrapper/v1/autoscrapper.proto\x12\x0fautoscrapper.v1\"\xb1\x01\n" +
	"\x13FindByFilterRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x19\n" +
	"\bmin_year\x18\x03 \x01(\rR\aminYear\x12\x19\n" +
	"\bmax_year\x18\x04 \x01(\rR\amaxYear\x12\x1b\n" +
	"\tmin_price\x18\x05 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x06 \x01(\x01R\bmaxPrice\"a\n" +
	"\x04Auto\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"C\n" +
	"\x14FindByFilterResponse\x12+\n" +
	"\x05autos\x18\x01 \x03(\v2\x15.autoscrapper.v1.AutoR\x05autos2t\n" +
	"\x13AutoScrapperService\x12]\n" +
	"\fFindByFilter\x12$.autoscrapper.v1.FindByFilterRequest\x1a%.autoscrapper.v1.FindByFilterResponse\"\x00B\xeb\x01\n" +
	"\x13com.autoscrapper.v1B\x11AutoscrapperProtoP\x01Zdgithub.com/diegoafg1009/auto-radar-scraping-microservice/pkg/genproto/autoscrapper/v1;autoscrapperv1\xa2\x02\x03AXX\xaa\x02\x0fAutoscrapper.V1\xca\x02\x0fAutoscrapper\\V1\xe2\x02\x1bAutoscrapper\\V1\\GPBMetadata\xea\x02\x10Autoscrapper::V1b\x06proto3"

var (
	file_autoscrapper_v1_autoscrapper_proto_rawDescOnce sync.Once
	file_autoscrapper_v1_autoscrapper_proto_rawDescData []byte
)

func file_autoscrapper_v1_autoscrapper_proto_rawDescGZIP() []byte {
	file_autoscrapper_v1_autoscrapper_proto_rawDescOnce.Do(func() {
		file_autoscrapper_v1_autoscrapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_autoscrapper_v1_autoscrapper_proto_rawDesc), len(file_autoscrapper_v1_autoscrapper_proto_rawDesc)))
	})
	return file_autoscrapper_v1_autoscrapper_proto_rawDescData
}

var file_autoscrapper_v1_autoscrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_autoscrapper_v1_autoscrapper_proto_goTypes = []any{
	(*FindByFilterRequest)(nil),  // 0: autoscrapper.v1.FindByFilterRequest
	(*Auto)(nil),                 // 1: autoscrapper.v1.Auto
	(*FindByFilterResponse)(nil), // 2: autoscrapper.v1.FindByFilterResponse
}
var file_autoscrapper_v1_autoscrapper_proto_depIdxs = []int32{
	1, // 0: autoscrapper.v1.FindByFilterResponse.autos:type_name -> autoscrapper.v1.Auto
	0, // 1: autoscrapper.v1.AutoScrapperService.FindByFilter:input_type -> autoscrapper.v1.FindByFilterRequest
	2, // 2: autoscrapper.v1.AutoScrapperService.FindByFilter:output_type -> autoscrapper.v1.FindByFilterResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_autoscrapper_v1_autoscrapper_proto_init() }
func file_autoscrapper_v1_autoscrapper_proto_init() {
	if File_autoscrapper_v1_autoscrapper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_autoscrapper_v1_autoscrapper_proto_rawDesc), len(file_autoscrapper_v1_autoscrapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_autoscrapper_v1_autoscrapper_proto_goTypes,
		DependencyIndexes: file_autoscrapper_v1_autoscrapper_proto_depIdxs,
		MessageInfos:      file_autoscrapper_v1_autoscrapper_proto_msgTypes,
	}.Build()
	File_autoscrapper_v1_autoscrapper_proto = out.File
	file_autoscrapper_v1_autoscrapper_proto_goTypes = nil
	file_autoscrapper_v1_autoscrapper_proto_depIdxs = nil
}
